#!/bin/sh

bat=/sys/class/power_supply/$(ls /sys/class/power_supply | grep BAT | head -n 1)/
per="$(cat "$bat/capacity")"

icon() {
  status="$(cat "$bat/status")"

  if [ status = "Charging" ]; then
    icon=""
  elif [ "$per" -gt "98" ]; then
    icon="󰁹"
  elif [ "$per" -gt "90" ]; then
    icon="󰂂"
  elif [ "$per" -gt "80" ]; then
    icon="󰂁"
  elif [ "$per" -gt "70" ]; then
    icon="󰂀"
  elif [ "$per" -gt "60" ]; then
    icon="󰁿"
  elif [ "$per" -gt "50" ]; then
    icon="󰁾"
  elif [ "$per" -gt "40" ]; then
    icon="󰁽"
  elif [ "$per" -gt "30" ]; then
    icon="󰁼"
  elif [ "$per" -gt "20" ]; then
    icon="󰁻"
  elif [ "$per" -gt "10" ]; then
    icon="󰁺"
    hyprctl notify 3 5000 "Battery Low.\n Connect Charger\!"
  elif [ "$per" -gt "0" ]; then
    icon="󰂃"
    hyprctl notify 3 5000 "Low Battery.\n Connect Char\!"
  else
    icon=""
  fi

  echo "$icon"
}

percent() {
  if [ -f "$bat" ]; then
    echo ""
  else
    echo $per
  fi
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
exit
