#!/bin/sh

calendar() {
    LOCK_FILE="$HOME/.cache/eww-calendar.lock"
    EWW_BAR="$HOME/.config/eww/bar"
    # EWW_BAR="$HOME/dotfiles/nixos/modules/desktops/modules/eww/.config/bar"

    run() {
        eww -c $EWW_BAR open calendar
    }

    # Run eww daemon if not running
    if [[ ! $(pidof eww) ]]; then
        eww daemon
        sleep 1
    fi

    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        run
    else
        eww -c $EWW_BAR close calendar
        rm "$LOCK_FILE"
    fi
}

if [ "$1" = "launcher" ]; then
    rofi
elif [ "$1" = "wifi" ]; then
    kitty -e nmtui
elif [ "$1" = "audio" ]; then
    pwvucontrol
elif [ "$1" = "calendar" ]; then
    calendar
fi
