#!/bin/sh

setBrightness() {
  percent="0.$1"
  xrandr --output $(xrandr -q | grep ' connected' | head -n 1 | cut -d ' ' -f1) --brightness $percent
}

getBrightness() {
  xrandr --verbose | grep -i brightness | cut -f2 -d ' ' | head -n1 | awk '{print $1 * 100}'
}

[ "$1" = "set" ] && setBrightness $2 && exit
[ "$1" = "get" ] && getBrightness && exit
exit
