#!/usr/bin/env sh

spaces() {
  WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
  ACTIVE=$(hyprctl monitors -j | jq '.[] | select(.focused) | .activeWorkspace.id')
  seq 1 5 | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc "map({id: . | tostring, windows: (\$windows[. | tostring]//0), active: (.==${ACTIVE})})"
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  if [[ $line == *"workspace"* ]]; then
    spaces
  fi
done
